source_catalog_name: HealthVerity_Claims_Sample_Patient_Dataset
source_schema_name: hv_claims_sample
target_catalog_name: agentic_hackathon
target_schema_name: yang_yang
service_date: '2021-12-21'
claim_id: 12390dfb568442cb957d5b3cfefe1119
patient_id: 4baf3314e4a181c5effcf2751fbe1e21
diagnosis_code: Z79899
ndc_code: '65162027250'
model_uc_name: agentic_hackathon.yang_yang.healthverity_clinical_assistant_dev
alias: Champion
endpoint_name: yang_yang_databricks_com-clinical_assistant_healthverity
experiment_path: /Workspace/Users/yang.yang@databricks.com/_agentic_hackathon/yyang_experiment 
label_users:
- yang.yang@databricks.com
